[[pages]]
path = "app.py"
name = "ğŸ  Accueil"

[[pages]]
path = "pages/01_Sources.py"
name = "ğŸ“‹ Sources"

[[pages]]
path = "pages/02_Lots.py"
name = "ğŸ“¦ Lots"

[[pages]]
path = "pages/03_Details_stock.py"
name = "ğŸ—ƒï¸ DÃ©tails Stock"

[[pages]]
path = "pages/04_Stock_Global.py"
name = "ğŸ“Š Stock Global"

[[pages]]
path = "pages/05_Planning_Lavage.py"
name = "ğŸ§¼ Planning Lavage"

[[pages]]
path = "pages/06_Previsions_Ventes.py"
name = "ğŸ“ˆ PrÃ©visions Ventes"

[[pages]]
path = "pages/07_Affectation_Stock.py"
name = "ğŸ”— Affectation Stock"

[[pages]]
path = "pages/08_Planning_Production.py"
name = "ğŸ­ Planning Production"

[[pages]]
path = "pages/09_Valorisation_Lots.py"
name = "ğŸ’° Valorisation Lots"
